# Generated by Django 4.2.6 on 2023-10-30 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qandeel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='century',
            options={'verbose_name_plural': 'Centuries'},
        ),
    ]
