# Generated by Django 4.2.6 on 2023-10-31 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qandeel', '0002_alter_century_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poem',
            new_name='PoeticFormat',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='poem',
            new_name='poetic_format',
        ),
    ]
