# Generated by Django 4.2.6 on 2023-10-31 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qandeel', '0003_rename_poem_poeticformat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Leave a comment')),
                ('status', models.CharField(choices=[('wa', 'Waiting'), ('ap', 'Approved'), ('na', 'Not Approved')], default='wa', max_length=2)),
                ('active', models.BooleanField(default=False)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='qandeel.section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
