# Generated by Django 4.2.7 on 2023-11-01 19:25

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('qandeel', '0009_alter_book_slug_alter_poet_slug_alter_section_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poet',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(allow_unicode=True, blank=True, editable=False, populate_from=['name'], unique=True),
        ),
    ]
