# Generated by Django 4.2.7 on 2023-11-04 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qandeel', '0013_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='poetic_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='qandeel.poeticformat'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
