# Generated by Django 4.2.7 on 2023-11-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qandeel', '0020_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
