# Generated by Django 4.2.7 on 2023-11-06 21:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qandeel', '0021_comment_created_at_comment_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poet',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
