# Generated by Django 4.2.7 on 2023-11-06 21:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qandeel', '0023_alter_book_description_alter_poet_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
