# Generated by Django 4.2.7 on 2023-11-06 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qandeel', '0024_alter_section_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='poet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='qandeel.poet'),
        ),
    ]
