# Generated by Django 4.2.7 on 2023-11-06 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qandeel', '0025_alter_book_poet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poet',
            name='century',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='poets', to='qandeel.century'),
        ),
    ]
