# Generated by Django 4.2.7 on 2023-11-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qandeel', '0027_alter_section_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='poet',
            name='image',
            field=models.ImageField(blank=True, upload_to='poet/poet_image/'),
        ),
    ]
