# Generated by Django 4.2.7 on 2023-11-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qandeel', '0029_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
