# Generated by Django 4.2.7 on 2023-11-10 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='datetime_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='datetime_modified',
            new_name='modified_at',
        ),
    ]
